---
- name: Include install tasks
  include_tasks: install.yml
  when: state | default('present') == 'present'

- name: Include uninstall tasks
  include_tasks: uninstall.yml
  when: state | default('present') != 'present'
